# Generated by Django 5.2.3 on 2025-06-30 17:45

import django_places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAddressFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('continent', django_places.models.ContinentField(blank=True, help_text='Continent as JSON', null=True)),
                ('country', django_places.models.CountryField(blank=True, help_text='Country as JSON', null=True)),
                ('state_province', django_places.models.StateProvinceField(blank=True, help_text='State/Province as JSON', null=True)),
                ('city', django_places.models.CityField(blank=True, help_text='City as JSON', null=True)),
                ('county', django_places.models.CountyField(blank=True, help_text='County as JSON', null=True)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
